name: Haskell School Deployment
on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development
jobs:
  Build-With-Jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          build_only: true
